import {
  QrCode,
  Globe,
  CreditCard,
  ShoppingCart,
  Table as TableIcon,
  Smartphone,
  Store,
  Package,
  Wallet,
  Users,
  BookOpen,
  BarChart3,
  Bike,
} from 'lucide-react';

export const featuresFeatures = [
  {
    title: 'POS System',
    icon: CreditCard,
    desc: 'Fast offline POS that works smoothly on Android devices',
    buttonText: 'See POS',
    buttonLink: '/pos',
  },
  {
    title: 'QR Code Menu',
    icon: QrCode,
    desc: 'Print once and update your entire menu instantly forever',
    buttonText: 'Explore QR Menu',
    buttonLink: '/qr-menu',
  },
  {
    title: 'Order Management',
    icon: ShoppingCart,
    desc: 'Send orders instantly from any table to the kitchen',
    buttonText: 'See Order Flow',
    buttonLink: '/order',
  },
  {
    title: 'Table Management',
    icon: TableIcon,
    desc: 'Smart table tools with merging bills and waiter calling',
    buttonText: 'View Tables',
    buttonLink: '/table',
  },
  {
    title: 'Digital Menu',
    icon: Smartphone,
    desc: 'Beautiful digital menus with photos that load instantly anywhere',
    buttonText: 'See Digital Menu',
    buttonLink: '/menu',
  },
  {
    title: 'Restaurant Website',
    icon: Globe,
    desc: 'Get a professional restaurant website with full online ordering',
    buttonText: 'Get Website',
    buttonLink: '/website-builder',
  },
  {
    title: 'Multi-Branch Control',
    icon: Store,
    desc: 'Easily manage every branch from one powerful unified dashboard',
    buttonText: 'Explore Multi-Branch',
    buttonLink: '/multi-branch',
  },
  {
    title: 'Inventory & Stock',
    icon: Package,
    desc: 'Track ingredients, control usage, and avoid waste automatically',
    buttonText: 'Track Inventory',
    buttonLink: '/inventory',
  },
  {
    title: 'Payment Integration',
    icon: Wallet,
    desc: 'Accept Telebirr, HelloCash, CBE Birr, or cash instantly anytime',
    buttonText: 'See Payments',
    buttonLink: '/payment-integration',
  },
  {
    title: 'Customer Management',
    icon: Users,
    desc: 'Build loyalty, manage customers, and store feedback easily',
    buttonText: 'Manage Customers',
    buttonLink: '/customer',
  },
  {
    title: 'Multi-Menu',
    icon: BookOpen,
    desc: 'Create different menus for branches or scheduled menu times',
    buttonText: 'Create Menus',
    buttonLink: '/multi-menu',
  },
  {
    title: 'Reports & Analytics',
    icon: BarChart3,
    desc: 'See sales insights, top sellers, and profit numbers instantly',
    buttonText: 'View Reports',
    buttonLink: '/reports-analytics',
  },
  {
    title: 'Delivery Management',
    icon: Bike,
    desc: 'Assign riders, track delivery status, and manage orders live',
    buttonText: 'Start Delivery',
    buttonLink: '/delivery',
  },
];

