import {
  QrCode,
  Globe,
  CreditCard,
  ShoppingCart,
  Table as TableIcon,
  Smartphone,
  Store,
  Package,
  Wallet,
  Users,
  BookOpen,
  BarChart3,
  Bike,
} from 'lucide-react';

export const featuresFeatures = [
  {
    title: 'POS System',
    icon: CreditCard,
    desc: 'Fast, offline POS on any Android device',
    buttonText: 'See POS',
    buttonLink: '/pos',
  },
  {
    title: 'QR Code Menu',
    icon: QrCode,
    desc: 'Print once, update forever — instantly',
    buttonText: 'Explore QR Menu',
    buttonLink: '/qr-menu',
  },
  {
    title: 'Order Management',
    icon: ShoppingCart,
    desc: 'Orders fly from table to kitchen',
    buttonText: 'See Order Flow',
    buttonLink: '/order',
  },
  {
    title: 'Table Management',
    icon: TableIcon,
    desc: 'Smart tables, call waiter, merge bills',
    buttonText: 'View Tables',
    buttonLink: '/table',
  },
  {
    title: 'Digital Menu',
    icon: Smartphone,
    desc: 'Beautiful mobile menu with photos',
    buttonText: 'See Digital Menu',
    buttonLink: '/menu',
  },
  {
    title: 'Restaurant Website',
    icon: Globe,
    desc: 'Professional site with online ordering',
    buttonText: 'Get Website',
    buttonLink: '/website-builder',
  },
  {
    title: 'Multi-Branch Control',
    icon: Store,
    desc: 'Manage 100+ branches from one login',
    buttonText: 'Explore Multi-Branch',
    buttonLink: '/multi-branch',
  },
  {
    title: 'Inventory & Stock',
    icon: Package,
    desc: 'Never run out or waste ingredients',
    buttonText: 'Track Inventory',
    buttonLink: '/inventory',
  },
  {
    title: 'Payment Integration',
    icon: Wallet,
    desc: 'Telebirr, CBE Birr, HelloCash + cash',
    buttonText: 'See Payments',
    buttonLink: '/payment-integration',
  },
  {
    title: 'Customer Management',
    icon: Users,
    desc: 'Loyalty, feedback, and customer history',
    buttonText: 'Manage Customers',
    buttonLink: '/customer',
  },
  {
    title: 'Multi-Menu',
    icon: BookOpen,
    desc: 'Different menus per branch or time',
    buttonText: 'Create Menus',
    buttonLink: '/multi-menu',
  },
  {
    title: 'Reports & Analytics',
    icon: BarChart3,
    desc: 'Know your best sellers and profits',
    buttonText: 'View Reports',
    buttonLink: '/reports-analytics',
  },
  {
    title: 'Delivery Management',
    icon: Bike,
    desc: 'Track riders, assign orders, real-time delivery',
    buttonText: 'Start Delivery',
    buttonLink: '/delivery',
  },
];
